name: dexef_datagrid_example
description: "Example app for the Dexef DataGrid package"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dexef_datagrid:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DexPro
      fonts:
        - asset: assets/fonts/DexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/DexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/DexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/DexPro-Regular.ttf
          weight: 600
        - asset: assets/fonts/DexPro-SemiBold.ttf
          weight: 600

