name: dexef_datagrid
description: A comprehensive and highly customizable Flutter DataGrid widget with advanced features like filtering, sorting, grouping, selection, editing, pagination, virtualization, and export functionality.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  csv:
  excel:
  pdf:
  printing:
  share_plus:
  path_provider:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
